apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mongo"
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: "mongo"
  template:
    metadata:
      labels:
        app: "mongo"
    spec:
      serviceAccountName: default
      containers:
      - name: "mongo"
        image: "mongo:latest"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-s
  labels:
    app: mongo
spec:
  type: NodePort
  selector:
      app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 27017
      nodePort: 30000
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider 
  labels:
    app: provider
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: ray2g/provider:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: provider-s
  labels:
    app: provider
spec:
  type: NodePort
  selector:
      app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30001
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats 
  labels:
    app: stats
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats
        image: ray2g/stats:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: stats-s
  labels:
    app: stats
spec:
  type: NodePort
  selector:
      app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 5001
      nodePort: 30002
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlations 
  labels:
    app: correlations
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: correlations
  template:
    metadata:
      labels:
        app: correlations
    spec:
      containers:
      - name: correlations
        image: ray2g/correlations:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: correlations-s
  labels:
    app: correlations
spec:
  type: NodePort
  selector:
      app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 5002
      nodePort: 30003
      targetPort: 5002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nginx-s-c
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-s-c
            port:
              number: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mongo-hpa
  namespace: default
  labels:
    app: mongo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongo
  minReplicas: 1
  maxReplicas: 399
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 200
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: provider-hpa
  namespace: default
  labels:
    app: provider
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: provider
  minReplicas: 1
  maxReplicas: 399
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 200
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stats-hpa
  namespace: default
  labels:
    app: stats
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stats
  minReplicas: 1
  maxReplicas: 399
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 200
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: correlations-hpa
  namespace: default
  labels:
    app: correlations
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: correlations
  minReplicas: 1
  maxReplicas: 399
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 200