apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider 
  labels:
    app: provider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: europe-west1-docker.pkg.dev/fcul123/cn-repo/provider:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: provider-s
  labels:
    app: provider
spec:
  selector:
    app: provider 
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
---      
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: provider-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: provider
  minReplicas: 3
  maxReplicas: 10
