apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: cn-deploy
spec:
  rules:
  - http:
      paths:
      - path: /provider
        pathType: Prefix
        backend:
          service:
            name: provider-s
            port:
              number: 8080  
      - path: /correlations
        pathType: Prefix
        backend:
          service:
            name: correlations-s
            port:
              number: 8080   
      - path: /analysis
        pathType: Prefix
        backend:
          service:
            name: analytics-s
            port:
              number: 8080
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-svc
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-svc
            port:
              number: 9090
