apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-ptt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-tt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 