apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-tt
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 
