apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-manager
rules:
- nonResourceURLs: ["/provider", "/provider/*","/correlations/*", "/analysis/*"] 
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guest-user
rules:
- nonResourceURLs: ["/correlations/*", "/analysis/*"] 
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guest-users
  namespace: default
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:unauthenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: guest-user 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-managers
  namespace: default
subjects:
- kind: User
  name: "group12-man"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: data-manager 
  apiGroup: rbac.authorization.k8s.io