name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build the Docker image provider
        run: docker build ./provider -t ${{secrets.DOCKER_USER}}/provider:latest
      
      - name: Docker Push provider
        run: docker push ${{secrets.DOCKER_USER}}/provider
      
      - name: Build the Docker image correlations
        run: docker build ./correlations -t ${{secrets.DOCKER_USER}}/correlations:latest
      
      - name: Docker Push correlations
        run: docker push ${{secrets.DOCKER_USER}}/correlations
      
      - name: Build the Docker image analytics
        run: docker build ./analytics_stats -t --tag ${{secrets.DOCKER_USER}}/analytics:latest
      
      - name: Docker Push analytics
        run: docker push ${{secrets.DOCKER_USER}}/analytics
